### ISSUE TITLE
Can not be used on Debian 9

### ISSUE THREAD

**Issue by jyzhang-bjtu** [bashtage/ng-numpy-randomstate#121]
My python is 3.5 and Numpy is 1.12 from Debian source on Debian 9. When I use randomstate, the error  msg is given as follows:
>>> import randomstate.prng.mt19937 as rnd
Traceback (most recent call last):
  File "__init__.pxd", line 1011, in numpy.import_array
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/randomstate/__init__.py", line 3, in <module>
    from randomstate.prng.mt19937 import *
  File "/usr/local/lib/python3.5/dist-packages/randomstate/prng/__init__.py", line 1, in <module>
    from .xorshift128 import xorshift128
  File "/usr/local/lib/python3.5/dist-packages/randomstate/prng/xorshift128/__init__.py", line 1, in <module>
    from .xorshift128 import *
  File "randomstate/xorshift128.pyx", line 28, in init randomstate.xorshift128
  File "__init__.pxd", line 1013, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by bashtage** [comment]
Sounds like the many Linux wheels require numpy 1.13 so you will need to build from source.

**Comment by bashtage** [comment]
You can use pip install randomstate --no-binary

**Comment by jyzhang-bjtu** [comment]
Thanks a lot. It works with numpy 1.13.
